Allow specifying UTC vs local timezone as program argument
zfsonlinux/zfs-auto-snapshot pull request #77
Opened 2017-12-22 15:51 UTC by jbnance

2017-12-27 21:41 UTC, behlendorf requested changes

2017-12-27 21:41 UTC, behlendorf commented on src/zfs-auto-snapshot.sh
> +  --longoptions=event:,keep:,label:,prefix:,local-tz:,sep: \
The `:` after `local-tz` needs to be removed because this option doesn't take an argument.  I'd also suggest moving it down in to the next line.

2017-12-27 21:41 UTC, behlendorf commented on src/zfs-auto-snapshot.sh
> +if [ -n $"opt_local_tz" ]
The `$` should be moved inside the quotes.

2017-12-27 21:48 UTC, jbnance commented
Fixed - thank you.

2017-12-27 21:55 UTC, behlendorf approved these changes

2018-02-13 21:13 UTC, UweSauter approved these changes

2018-02-13 21:19 UTC, UweSauter requested changes
opt_local_tz='' should be inserted after line 44 in zfs-auto-snapshot.sh

2018-02-13 22:04 UTC, jbnance commented
I added `opt_local_tz` default as requested.  Thank you for pointing it out.

2018-02-13 22:38 UTC, UweSauter approved these changes

2018-06-04 22:27 UTC, marcopaganini commented
Any plans to merge this? I'd really like to keep my snapshots in local time.

2018-07-12 16:53 UTC, openspork approved these changes

2019-03-07 12:54 UTC, Lynxy commented
How has this not been merged yet? I recently started using zfs-auto-snapshot and have found it really annoying that the snapshot names are all in UTC without any mention of UTC at all!

For me times are off by 5 hours. Imagine I have this script set to run at midnight, but something bad happened at 11pm. The next morning I catch the error and want to rollback snapshots.. oh but wait the most recent one is labeled 5am, well after the bad thing occurred at 11pm, guess I need to rollback even further. How is this acceptable?

I'll be manually patching my local script with this PR but strongly urge that this PR be accepted for the sanity of users everywhere.

2019-04-01 14:55 UTC, jrmiller82 commented
Please merge this for the love of all of us who don't want to do UTC calculations on our snapshots. :)

2020-02-02 05:21 UTC, atomicwrites commented
Any plans to merge this?

2020-09-20 14:39 UTC, erratic-c-programmer commented
Please merge this, it's rather troublesome having to add 8 hours to timestamps manually every time...

2020-12-10 05:08 UTC, gdi2k commented
Would also love to see this merged. We give end users access to their snapshots; confusion abounds over time stamps not matching local time.

2020-12-10 10:40 UTC, alkisg commented
A workaround is to use `faketime`:

```shell
$ crontab -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

10,20,30,40,50 * * * * faketime "+8 hours" zfs-auto-snapshot -q -g --label=10minutely --keep=24 //
0 1-23 * * * faketime "+8 hours" zfs-auto-snapshot -q -g --label=hourly --keep=24 //
0 0 2-7,9-14,16-21,22-31 * * faketime "+8 hours" zfs-auto-snapshot -q -g --label=daily --keep=7 //
0 0 8,15,22 * * faketime "+8 hours" zfs-auto-snapshot -q -g --label=weekly --keep=4 //
0 0 1 * * faketime "+8 hours" zfs-auto-snapshot -q -g --label=monthly --keep=4 //
```

2024-08-24 15:59 UTC, Guiorgy commented
Made a fork to use this and other PRs, and while at it, I checked other forks to see if there's anything interesting to gather. It's funny that most of them were simple forks that removed the `-u` (UTC) flag 😃

2025-02-11 04:28 UTC, compumatter commented
On our Ubuntu server, this will put a local time on each snapshot label.  I didn't want to take a chance with faketime @alkisg just not sure of emergency restore issues if it has some internal conflicts that may crop up.  Just don't know.

This ensures you know what time it is and zfs does what they always do.  The use of flock ensures snapshots don't trip over each other and up your resources.  You can remove that if you want to run without.

PATH="/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

# 15min snapshots - Keep last 24hrs (96 snapshots)
*/15 * * * * root flock -n /var/run/zfs-auto-snapshot.lock sh -c 'LOCAL_TIME=$(date +\%Y_\%m_\%d_\%H\%M); zfs-auto-snapshot --syslog --label=15min_${LOCAL_TIME} --keep=96 // 2>/var/log/zfs-snapshots.log'

# Daily snapshots - Keep last 15 days (15 snapshots)
30 0 * * * root flock -n /var/run/zfs-auto-snapshot.lock sh -c 'LOCAL_TIME=$(date +\%Y_\%m_\%d_\%H\%M); zfs-auto-snapshot --syslog --label=daily_${LOCAL_TIME} --keep=15 // 2>/var/log/zfs-snapshots.log'

# Weekly snapshots - Keep last 4 weeks (4 snapshots)
15 0 * * * root flock -n /var/run/zfs-auto-snapshot.lock sh -c 'LOCAL_TIME=$(date +\%Y_\%m_\%d_\%H\%M); zfs-auto-snapshot --syslog --label=weekly_${LOCAL_TIME} --keep=4 // 2>/var/log/zfs-snapshots.log'

# Monthly snapshots - Keep last month (1 snapshot)
0 0 1 * * root flock -n /var/run/zfs-auto-snapshot.lock sh -c 'LOCAL_TIME=$(date +\%Y_\%m_\%d_\%H\%M); zfs-auto-snapshot --syslog --label=monthly_${LOCAL_TIME} --keep=1 // 2>/var/log/zfs-snapshots.log'

2025-09-01 06:04 UTC, closed without merging